name = "JSPCD"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f51d6022474423e3596cfcf9c9e48d31f650e14c0f740868fdb55a735ecbf76"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"

[options]
no-internal-hashes = false
