name = "JSPCD"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f083aee1dbcd8e7e1f1d26adee50c02eebaed174f2035e1a8deeb9161912e0b6"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"

[options]
no-internal-hashes = false
