name = "JSPCD"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a37ec1741bfc1af98a3b7c881bc707a8d67cb026b4cdaaf0b692cac04b80306"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"

[options]
no-internal-hashes = true
