name = "JSPCD"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5c80bdc670cab3f674d1544e9beab89e67c77133e75f9ce346a0df44292ebed"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"

[options]
no-internal-hashes = true
