name = "JSPCD2"
author = "Codion"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a49e90fd730c5224ecf191b2b1a72b61333c0d8422582e7742b5d307361c08b"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
