name = "JSPCD"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f482823d082c27d7061729b0708be1d2eecafdcddfa239e014097f2a4fac6b17"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
