name = "JSPCD"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "851ae77bd729795d8de16c891194ff4fee7704c6ca8ad98ef4e6dc1a3de45718"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"

[options]
no-internal-hashes = false
