name = "JSPCD2"
author = "Codion"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ee8892b2878673c4844b48b366fc484f613e0c6a70da24e5d73bd904a23a83c"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
