name = "JSPCD2"
author = "Codion"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "548086d32f4dfa022b6b921da57a43f35f61262ce799423da731f40fb274a2e3"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
