name = "JSPCD"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1dda8f08ef3f7a67559bc70afa905eea8ae245344d296a90fd456d8d20ad7f00"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"

[options]
no-internal-hashes = false
