name = "JSPCD"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "869353fdcd71d485a0f39689878f22a96b638b7388b2cc4b8629efd3e6686034"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"

[options]
no-internal-hashes = true
