name = "JSPCD"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76ac580dd57447bba468818b642c45503b416fb03560a1b39423d51c437b705c"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"

[options]
no-internal-hashes = true
