name = "JSPCD"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "153956f8afda1bfa25178600f305dfdc6204678acd645f97b4166c7755e335ff"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
