name = "JSPCD2"
author = "Codion"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f5458b1d9bf87ca589bf7f031d33f83b0316e81694035ecd08f14f2c363049e"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
