name = "JSPCD"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22dedd0c9d2d062676909eb69e11b4843664040fb0498489ca458224db189633"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"

[options]
no-internal-hashes = false
