name = "JSPCD"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b069712cff76a401c1c502167e5330a827f8424ff39ff77e942ee8816de1286d"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"

[options]
no-internal-hashes = true
