name = "JSPCD2"
author = "Codion"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6d10e0f3b9fc2052c58e0d5f9847faf5db455ca4fc948e13f4de353a52b6fa6"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
