name = "JSPCD2"
version = "10.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ee324e829ae718a2545d15b24f3a6c5c0047dcec46b6770e957c302df848408"

[versions]
forge = "47.2.16"
minecraft = "1.20.1"

[options]
no-internal-hashes = false
