name = "JSPCD"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec2e0b39a37096c40d541561686707857c4bf1905beb71a4215bfd1dba1eb693"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"

[options]
no-internal-hashes = false
