name = "JSPCD2"
author = "Codion"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1508c86e9c6a16b8f518ac06852720e682e38db1dff94f73c8ff620331cc5f1e"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
