name = "JSPCD2"
author = "Codion"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3d914916ca246a66d7510b940488a37db4d1ee74421b8d3ae759b7ed80c7d3b"

[versions]
fabric = "0.15.9"
minecraft = "1.20.1"
